### ISSUE TITLE
hotkey E

### ISSUE THREAD

**Issue by tidebre67** [cleidigh/EditEmailSubject-MX#33]
in principle it works pretty good in TB 78, but i found that hotkey "E" does not work.

**Comment by jobisoft** [comment]
E is taken now by "Edit as new". Do you see any free letter in the menu, which we could use instead?

**Comment by mattslay** [comment]
Maybe "**S**" for "**Subject**"

**Comment by exapplerep** [comment]
> Maybe "**S**" for "**Subject**"

Whatever works is fine with me. 👍

**Comment by tidebre67** [comment]
@John, wonder a bit, as upto TB68 Strg E was for 'Edit as new' and E only (without strg) hotkey E for EditEmailSubject. In TB78 strg E is still for Edit as new.

**Comment by exapplerep** [comment]
I'll respectfully suggest you (developer) pick a free letter, identify it as the hotkey in the menu choice (if possible), and just do it. Don't wait for a consensus on this; it's not necessary. :D

**Comment by RealRaven2000** [comment]
"pick a free letter" - that is actually a tall order, and cannot be answered 100% truthfully. :P

**Comment by pdcweb** [comment]
Just upgraded to 78.4.0 and had to move to this new add on for editing email subjects. Thanks for providing it!

We use the E key constantly for efficient work flow and now we cannot. Please pick a new free letter as soon as possible.

Or perhaps somebody can post instructions on how to make TBKeys launch the Edit Subject command?

**Comment by Albaldah** [comment]
> Just upgraded to 78.4.0 and had to move to this new add on for editing email subjects. Thanks for providing it!
> We use the E key constantly for efficient work flow and now we cannot. Please pick a new free letter as soon as possible.
> Or perhaps somebody can post instructions on how to make TBKeys launch the Edit Subject command?
Exactly the same here! Maybe a TB geek can tell us how to "script" or whatever tbkeys command to invoke EES-MX.

**Comment by morat523035** [comment]
You could remove the access key from the "Edit As New Message" menu item using the userChromeJS extension.

http://forums.mozillazine.org/viewtopic.php?f=39&t=3066910

**Comment by Llaves** [comment]
I'm confused. Edit as New is ctrl-e and has not been a conflict with e for edit subject line in the past? Why is this now perceived as a problem?

**Comment by pdcweb** [comment]
> I'm confused. Edit as New is ctrl-e and has not been a conflict with e for edit subject line in the past? Why is this now perceived as a problem?

"ctrl-e" is not the issue. "e" by itself is the issue. 
"E" used to launch the Edit email subject dialog for the selected message in the mail list.

**Comment by Llaves** [comment]
> "ctrl-e" is not the issue. "e" by itself is the issue.
> "E" used to launch the Edit email subject dialog for the selected message in the mail list.

I thought the whole point was to enable it to launch the Edit email subject.
"E"  or "e" does nothing on my T'bird, 78.5.1 in any of the panes.

**Comment by Elliott599** [comment]
I agree with Llaves.  "E" or "e" does nothing in Tbird 78.6.  Ctrl-E and Alt-E perform operations, but not just an "e."  Have you tried it?  Or pick another letter, or even Ctrl-Shift-e would work.  But please provide a Hot Key.  Thank you.

**Comment by Elliott599** [comment]
Just made a contribution.  Thank you for the program.  I was unwilling to move to TBird 78 until I had a replacement for HeaderTools Lite.  Your program works great but you really need a hotkey.  Why not just use the same one that HeaderTools Lite provided - Ctrl-H?  Please do this soon.  Thank you.

**Comment by TossOne53** [comment]
Same problem here, long time use but new to TB 78.6.0 on Win10 and the letter E is not working as a hotkey.  Very much looking forward to a hotkey solution.

**Comment by MWH-Rookie** [comment]
Hello everyone,
I like your extension very much. But I miss the hotkey e very much. Right now I do not want to install another app for hotkey customization. This is just because I only found one extension that might work (at least some reports say that) and that requires permission to access the entire computer. I would rather love to learn how to define a hotkey on my own. I found suggestions that these could be defined in dtd files in earlier TB versions, but this seems to have changed. Therefore I would kindly ask you how to define a different hotkey. I am using TB 78 on my Ubuntu 20.04.
Thanks a lot!

**Comment by pdcweb** [comment]
Why is this closed? Is there a working shortcut fix available for download already?

**Comment by jobisoft** [comment]
github seems to close issues when they are mentioned in a commit which also includes the word "fix".

**Comment by jobisoft** [comment]
[EES_4_4.zip](https://github.com/cleidigh/EditEmailSubject-MX/files/6175563/EES_4_4.zip)

This works for me on Windows. When a message is selected and I press CTRL+SHIFT+E the edit popup is opened.

I got reports it still does not work, which OS?

**Comment by MWH-Rookie** [comment]
Now it seems to work. Thank you!
The last problem may have been caused by me tinkering with the omni.ja and forgetting to fully restore it. But now I have reinstalled TB 78 and after that also reinstalled your addon version 4.4. And now it works. Thanks a lot!
Can I buy you a cup of coffee via paypal?

**Comment by jobisoft** [comment]
This add-on was updated in a group effort and we decided to redirect donations to Thunderbird.
https://give.thunderbird.net/en-US/

But if you really want to support me directly:
https://www.paypal.com/paypalme/johnbieling

**Comment by pdcweb** [comment]
Forgive me, but where does one put the contents of the zip file to try it?

**Comment by jobisoft** [comment]
In the add-on manager there is a gear icon:

![image](https://user-images.githubusercontent.com/5830621/111870554-b8433500-8985-11eb-814e-a2a74e89b687.png)

Select `Install Add-on From File` and select the zip file.

**Comment by pdcweb** [comment]
Fantastic, thank you. The update works for me.

**Comment by MWH-Rookie** [comment]
Dear John
I did both. It would be great if there was kind of a general explanation for me like me who are not that skilled how to enable such hotkeys. And if it is only for learning purposes.
Have a nice day!

**Comment by jobisoft** [comment]
> 
> 
> Dear John
> I did both. It would be great if there was kind of a general explanation for me like me who are not that skilled how to enable such hotkeys. And if it is only for learning purposes.
> Have a nice day!

What is the scope of that question? As a user of the add-on to learn how to use hotkeys in Thunderbird? Or as a developer to learn how to modify add-ons so they accept hotkeys?

**Comment by pdcweb** [comment]
Thanks for all your hard work here John!

`	"commands": {
	  "edit_email_subject": {
		"suggested_key": {
		  "default": "Ctrl+Shift+E"
		},
		"description": "Open the Edit Email Subject popup"
	  }`

This bit of code may imply that it is possible to change the key selection. 
Is there an easy way of assigning a different key now?

**Comment by MWH-Rookie** [comment]
You're right. This appears to be unclear. No, I am no developer of TB or its addons, but sometimes I try to enhance the software that I use (not always successfully). Right now, I have actually search several days for a solution and did not ask right away in the forum or on topicbox or here. Instead I really tried to figure out on my own, how this can be done with a current addon and the new TB version. But I found only outdated advice or advice that relied on further addons. Therefore I could imagine that this fix seemed very obvious for experienced developers like you, but I can just say that it was hard for me to figure that out as I did not know anything about TB's architecture before. Actually I learned many new things during the past days. Still, I would not have found the solution without your help. And therefore I would just try to speak for interested people like myself who occasionally would try something like this. And who knows, perhaps it leads to further efforts in the future.

**Comment by jobisoft** [comment]
Hi MWH Rookie,

first of all: do not be afraid to ask. If you do not want to have your question out in the open on discuss.thunderbird.net, you can also join the add-on developer chat. I am there most of the time:
https://chat.mozilla.org/#/room/#tb-addon-developers:mozilla.org

Now regarding your question: As a user it is not possible to change the hotkey defined by an add-on. It would be a great enhancement if Firefox and Thunderbird would actually have a hotkey config, which sounds doable, as every add-on has to register the hotkey it wants to use. So Firefox and Thunderbird know them and could allow the user to remap them. As Thunderbird is based on Firefox, this is a feature request which should be filed at Firefox.

The developer could add an option to its own add-on option to let the user change the key.

If you want to learn more about add-on development: The developer.thunderbird.net page has an introduction:
https://developer.thunderbird.net/add-ons/mailextensions

The API details are here:
https://webextension-api.thunderbird.net/en/latest/

**Comment by MWH-Rookie** [comment]
Thank you! I will take a look into the introduction. :)

**Comment by MWH-Rookie** [comment]
And about being afraid: No I am not. But I did not know where the right place to ask would be (github, topicbox, mozillazine forums, etc.)

**Comment by jobisoft** [comment]
Those are our official community channels:
https://developer.thunderbird.net/add-ons/community

And of course the github issue section of a given add-on, if it is not a general development question.

**Comment by pdcweb** [comment]
For those who are finding the Ctrl+Shift+E combination a bit cumbersome... 

I found that I could use windows powertoys keyboard manager to map to remap the shortcut Alt+E which is much easier to do one handed.

![image](https://user-images.githubusercontent.com/73648657/112631097-75111800-8e04-11eb-96ae-040815c19108.png)

**Comment by bege10** [comment]
> 
> 
> [EES_4_4.zip](https://github.com/cleidigh/EditEmailSubject-MX/files/6175563/EES_4_4.zip)
> 
> This works for me on Windows. When a message is selected and I press CTRL+SHIFT+E the edit popup is opened.
> 
> I got reports it still does not work, which OS?

It works on Windows 10, but only in the main window, not in the message window https://github.com/cleidigh/EditEmailSubject-MX/issues/42

**Comment by bege10** [comment]
> Now regarding your question: As a user it is not possible to change the hotkey defined by an add-on. It would be a great enhancement if Firefox and Thunderbird would actually have a hotkey config, which sounds doable, as every add-on has to register the hotkey it wants to use. So Firefox and Thunderbird know them and could allow the user to remap them. As Thunderbird is based on Firefox, this is a feature request which should be filed at Firefox.
> 
> The developer could add an option to its own add-on option to let the user change the key.
> 
Maybe I misunderstand this discussion, but both Firefox and Thunderbird do have this feature.

![Screenshot_271](https://user-images.githubusercontent.com/1184237/114137849-0f954f00-990d-11eb-97ba-c80a600dc79d.png)

**Comment by jobisoft** [comment]
Wow. I did not know that, What are the steps to get there?

**Comment by bege10** [comment]
![Screenshot_272](https://user-images.githubusercontent.com/1184237/114142198-ed9ecb00-9912-11eb-90f1-fef78dc20833.png)

**Comment by jobisoft** [comment]
👏 

OT: What version of TB are you using, or how did you get the delete button into the add-on list? I added the wrench button in TB Beta, but where does the delete button come from?

**Comment by bege10** [comment]
> OT: What version of TB are you using, or how did you get the delete button into the add-on list? I added the wrench button in TB Beta, but where does the delete button come from?

They come from Aris' CSS tweaks for Firefox that also work for Thunderbird. There are many more tweaks, I only use the Addon Manager tweaks.
https://github.com/Aris-t2/CustomCSSforFx/releases

**Comment by RealRaven2000** [comment]
Good find on the shortcut configurator, however it seems Thunderbird cannot detect any shortcuts that I have declared with my own ADd-ons dynamically (from JS code, because my Add-ons offer its own configurable shortcut options) :

![image](https://user-images.githubusercontent.com/6314674/114146312-54ba8080-990f-11eb-9573-47d085d90325.png)

Is there a way to register the shortcuts from (privileged) code when I set up my keyboard listener, so that they are seen by this feature?

**Comment by jobisoft** [comment]
@RealRaven2000 : That only works for shortcuts using the commands WebExtension API.

**Comment by jobisoft** [comment]
Edit: You can use the notifyTools to connect WebExtension Shortcuts to your legacy code.

**Comment by RealRaven2000** [comment]
> You can use the notifyTools to connect WebExtension Shortcuts to your legacy code.
> 
> https://github.com/thundernest/addon-developer-support/wiki/Tutorial:-Convert-add-on-parts-individually-by-using-a-messaging-system
> 
> Edit: Added Link.

Ok, so maybe the keyboard listener can be the first thing to go. Hope I can still distinguish which part of the screen (originalTarget / parentnodes) has focus. ideally it's just a glorified event listener in the background code.

**Comment by pdcweb** [comment]
Good find on the shortcut configurator, unfortunately it does not work with ALT+E for me. I only end up with the menu opening. I'll have to stick with the keyboard manager powertoy for now.

**Comment by jobisoft** [comment]
See here:
https://github.com/cleidigh/EditEmailSubject-MX/issues/33#issuecomment-803312644

This fixed it but uses CTRL+SHIFT+E

**Comment by jobisoft** [comment]
I think we are ok with publishing this? Works for everybody?

**Comment by bege10** [comment]
> 
> 
> I think we are ok with publishing this? Works for everybody?

It works for the main window. Can you add the shortcut and the context menu item also for the  of the message window?

**Comment by jobisoft** [comment]
Did the old version do that? This involves reloading the message and at the moment I do not want to go there.

**Comment by pdcweb** [comment]
> See here:
> [#33 (comment)](https://github.com/cleidigh/EditEmailSubject-MX/issues/33#issuecomment-803312644)
> 
> This fixed it but uses CTRL+SHIFT+E

CTRL+SHIFT-E works for me, but as seen in BEGE10's example: https://github.com/cleidigh/EditEmailSubject-MX/issues/33#issuecomment-816442815 setting ALT-E does not work for me.

I have ALT-E working by remapping it to CTRL+SHIFT-E for TB using the keyboard mapper powertoy as stated previously.
https://github.com/cleidigh/EditEmailSubject-MX/issues/33#issuecomment-808176079

I find CTRL+SHIFT-E cumbersome as it needs 2 hands.

**Comment by pdcweb** [comment]
> Did the old version do that? This involves reloading the message and at the moment I do not want to go there.

Yes, the old version did this. You could change the subject of whatever message you were currently viewing.

**Comment by jobisoft** [comment]
> CTRL+SHIFT-E works for me, but as seen in BEGE10's example: #33 (comment) setting ALT-E does not work for me.

We switched away from ALT-E as that was consumed by some other internal TB shortkey, I do not think we can fix that. I do not know if "ALT" is the issue or "E", but with Thunderbirds built in shortcut definition dialog, you could try to play with other combinations and maybe you find a single-hand combination which works. We could that think about using it as default.

**Comment by jobisoft** [comment]
> Yes, the old version did this. You could change the subject of whatever message you were currently viewing.

I would move this to another issue and handle it later. Lets get this version out soon.

**Comment by pdcweb** [comment]
>I do not know if "ALT" is the issue or "E", but with Thunderbirds built in shortcut definition dialog, you could try to play with other combinations and maybe you find a single-hand combination which works. We could than think about using it as default.

ALT+S is available and works.

**Comment by bege10** [comment]
> We switched away from ALT-E as that was consumed by some other internal TB shortkey, I do not think we can fix that. I do not know if "ALT" is the issue or "E", but with Thunderbirds built in shortcut definition dialog, you could try to play with other combinations and maybe you find a single-hand combination which works. We could than think about using it as default.

I am fine with ALT+E, don't know why that does not work for others. The old version I had remapped to F2 with a script because that is the key to change names in several Windows programs, but the new TB tool does not allow that.

**Comment by jobisoft** [comment]
To wrap this up: ALT + S works for everybody? I will submit v4.4 to ATN on Monday with ALT + S as default if I do not get negative feedback.

**Comment by Elliott599** [comment]
I have Win10 on a 64bit machine and Tbird 78.9.1.  When in TBird and I press Alt + S nothing now happens so it does not appear to be assigned, so that should work.  However, I have gotten used to using Right Click and scrolling down to the very bottom of the list of options (glad it is at bottom) and that works fine.  I hope that option remains even after you add the hotkey.

**Comment by jobisoft** [comment]
> 
> 
> I have Win10 on a 64bit machine and Tbird 78.9.1. When in TBird and I press Alt + S nothing now happens so it does not appear to be assigned, so that should work. However, I have gotten used to using Right Click and scrolling down to the very bottom of the list of options (glad it is at bottom) and that works fine. I hope that option remains even after you add the hotkey.

You have to install version 4.4 from [here](https://github.com/cleidigh/EditEmailSubject-MX/issues/33#issuecomment-803312644) and you have to manually set ALT + S as described [here](https://github.com/cleidigh/EditEmailSubject-MX/issues/33#issuecomment-816464926) to test this. Is this what you did?

**Comment by Elliott599** [comment]
Sorry I was unclear.  I have not installed 4.4  I am still using 4.3.  I was just confirming that nothing else in my Thunderbird appears to use Ctrl + S and was hoping that the Right Click feature will still work in 4.4.

**Comment by exapplerep** [comment]
Ctrl-Shift-E works nicely. Contextual-menu continues to work as before. Thank you.

**Comment by dvschuetz** [comment]
I tested it.
On Windows 10 Pro 21H1 with TB 78.14.0 (both German) the EES Version 4.4 (from [here](https://github.com/cleidigh/EditEmailSubject-MX/files/6175563/EES_4_4.zip)) works fine with Ctrl-Shift-e in the message list. 

My comments and suggestions:
The "Details" (description) does not mention any hotkey - this could be helpful.

(    a propos, the details also do not mention yet, that the original message gets added two lines:
          X-EditEmailSubject: [date and time]
          X-EditEmailSubject-OriginalSubject: [original subject]
     This would be good to know for business users, either. )

In AddOn-Management ->Settings -> Manage Hotkeys (Screenshot [here](https://github.com/cleidigh/EditEmailSubject-MX/issues/33#issuecomment-816464926)) the hotkey appears and may be changed by the user, but only in combination with other functionkeys like Strg/Ctrl, Shift or Alt, not without any functionkey (like the old AddOn until TB 51 with just "e").

In the context menu there is a line "Edit Email Subject", in german localization with an underlined first E, but the hotkey is not mentioned - this would be nice.
In the main menu "Message": "Edit Email Subject" does not appear at all, yet.

![grafik](https://user-images.githubusercontent.com/5382362/133810881-b1da2416-61d7-47b9-9663-7a871a2a447c.png)

Many of my customers would be glad to download the new release from the main repository addons.thunderbird.net. Thank you so much!

**Comment by jobisoft** [comment]
I removed the wrong/hardcoded hotkey defs from the locale strings. Please file a new issue for dynamically adding the currently (user-) defined hotkey to the menu entry.

Adding a menu entry to the message menu is currently not possible with WebExtension, do not know if we ever can.

**Comment by dvschuetz** [comment]
thank you for your effort.

Am 15. Oktober 2022 22:39:21 MESZ schrieb John Bieling ***@***.***>:
